name: Integration Test

on: push

jobs:
  build:

    runs-on: macOS-latest

    container:
      image: elixir:1.9.1

    steps:
    - uses: actions/checkout@v1
    - name: Install Lux Testing Tool
      run: |
        git clone https://github.com/hawk/lux.git
        cd lux
        autoconf
        ./configure
        make
        cd ..
    - name: Run Tests
      run: lux/bin/lux -v --timeout=20000 integration_test/integration_test.lux
