name: Integration Test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1

    steps:
    - uses: actions/checkout@v1
    - name: Install Lux Testing Tool
      run: |
        git clone https://github.com/hawk/lux.git
        cd lux
        autoconf
        ./configure
        make
        cd ..
    - name: Install Linux filesystem watcher depdency
      run: sudo apt-get install inotify-tools
    # - name: Install example app deps
    #   run: |
    #     cd integration_test/example_app
    #     MIX_ENV=test iex -S mix do local.hex --force, local.rebar --force, deps.get
    #     cd ../..
    - name: Run Tests
      run: lux/bin/lux -v --timeout=20000 integration_test/integration_test.lux
