name: Integration Test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1

    steps:
    - uses: actions/checkout@v1
    - name: Install Lux Testing Tool
      run: |
        git clone https://github.com/hawk/lux.git
        cd lux
        autoconf
        ./configure
        make
        cd ..
    - name: Install Linux filesystem watcher depdency
      run: |
        apt-get update
        apt-get install -y inotify-tools
    - name: Get and compile dependencies of test projects to circumvent timeout errors during test execution
      run: |
        cd integration_test/simple_example_app
        MIX_ENV=test iex -S mix do local.hex --force, local.rebar --force, deps.get, compile
        cd ../..
        cd integration_test/phoenix_example_app
        MIX_ENV=test iex -S mix do local.hex --force, local.rebar --force, deps.get, compile
        cd ../..
    - name: Run Tests
      run: lux/bin/lux -v integration_test/simple_example_app/integration_test.lux integration_test/phoenix_example_app/integration_test.lux
