name: Integration Test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        git clone https://github.com/hawk/lux.git
        cd lux
        autoconf
        ./configure
        make
        cd ..
    - name: Run Tests
      run: lux/bin/lux integration_test/integration_test.lux
