name: Integration Test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Install Lux Testing Tool
      run: |
        git clone https://github.com/hawk/lux.git
        cd lux
        autoconf
        ./configure
        make
        cd ..
    - name: Install Linux filesystem watcher depdency
      run: |
        apt-get update
        apt-get install -y inotify-tools
    - name: Get and compile dependencies of test projects to circumvent timeout errors during test execution
      run: |
        cd integration_test/simple_example_app
        MIX_ENV=test mix do local.hex --force, local.rebar --force, deps.get, compile
        cd ../..
        cd integration_test/phoenix_example_app
        MIX_ENV=test mix do local.hex --force, local.rebar --force, deps.get, compile
        cd ../..
    - name: Run Tests
      run: lux/bin/lux -v integration_test/simple_example_app/integration_test.lux integration_test/phoenix_example_app/integration_test.lux
      env:
        # use postgres for the host here because we have specified a container for the job.
        # If we were running the job on the VM this would be localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}